stages:
- name: "2"
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: "2"
- name: "3"
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: "4"
- name: "5"
  steps:
  - runScriptConfig:
      image: php:latest
      shellScript: "5"
- name: "6"
  steps:
  - runScriptConfig:
      image: java:6
      shellScript: "6"
- name: "7"
  steps:
  - runScriptConfig:
      image: java:7
      shellScript: "7"
- name: "9"
  steps:
  - runScriptConfig:
      image: java:7
      shellScript: "7"
- name: "8"
  steps:
  - runScriptConfig:
      image: php:latest
      shellScript: "8"
timeout: 60
notification: {}
